version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5281:5281"
    volumes:
      - ./urlshortener.db:/app/urlshortener.db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: ./url-shortener-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend